# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: docs-next
description: Dwolla Developer Portal
author:
  name: Dwolla
  email: api@dwolla.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: false

# Markdown library
markdown: redcarpet

redcarpet:
  extensions: ['fenced_code_blocks', 'smart', 'tables']

highlighter: rouge

# Sitemap
url: https://developers.dwolla.com
gems:
  - jekyll-sitemap
